Correct run-tests documentation to observed behaviour
racket/rackunit pull request #137
Opened 2021-03-24 21:50 UTC by wilbowma

Addresses #135

2021-03-24 22:06 UTC, mflatt requested changes

2021-03-24 22:06 UTC, mflatt commented on rackunit-doc/rackunit/scribblings/ui.scrbl
> +@racket[current-error-port] when there are test failurese.
Typo: "failurese".

2021-03-24 22:06 UTC, mflatt commented on rackunit-doc/rackunit/scribblings/ui.scrbl
> +example, by (X)Emacs's compile function)
Another nit: It looks like the sentence needs an ending `.` (and needed it before your changes).

2021-04-10 00:51 UTC, wilbowma commented
I fixed those typos; I marked them as resolved, but github still shows this as unsolved and I don't know why.

2021-04-10 11:55 UTC, samth commented
This has conflicts with the main branch, can you fix that?

2021-04-11 00:49 UTC, wilbowma commented
I've rebased on the main branch.

2021-04-11 04:20 UTC, samth commented
The typo noted by @mflatt seems to still be there.

2021-04-11 11:54 UTC, merged